### ISSUE TITLE
Options is not rendered back to the fields.

### ISSUE THREAD

**Issue by ghost** [frekw/kirby-modules#1]
Hi man,
# This is probably the most epic field/plugin ever created for Kirby, big thanks !!

Found an issue about options, once you fill in the options in the panel it´s
saves the value to the text file, but not to the fields in the panel/admin, so if
you hit save again it clear the values in the text file as well...

Toolkit version: 2.2.3
Kirby version: 2.2.3
Panel version: 2.2.3

**Comment by ghost** [comment]
If you guys want some more cred and fame, 
please add/show your plugin to community https://forum.getkirby.com/

**Comment by frekw** [comment]
Hey!

Thanks for compliments (and the report)! I'm glad to hear you like it :)

Yeah – I noticed that was the case earlier today! I'll try to fix it first thing in the morning. This is still very much a work in progress!

I'm planning on posting it to the forums once I've gathered some feedback. Just trying to make sure the approach is sound before I get too many other people committed to it :)

**Comment by ghost** [comment]
Cool !
