### ISSUE TITLE
module init + checkbox problem

### ISSUE THREAD

**Issue by dirkschmid** [frekw/kirby-modules#13]
Hi,
1. after the last update i could not use the the modules anymore, cause you changed the initialization, it was this:  `<?php echo $page->modules()->modules() ?>` what changed?
2. and i discovered a problem with options, if i set a checkbox. it only get's rendered if its checked, so i get an error if it's unchecked, in the template cause its not there.

Any help?

**Comment by frekw** [comment]
Hey!

Nothing should have changed in terms of how the modules are rendered, `<?php echo $page->modules()->modules() ?>` is still be the way to do it.

In regards to the checkboxes I use them in multiple places without any issues. In order to reproduce this I need more info, preferably with examples.

But due to time constraints I can't make any promises that I'll have time to dig into the underlying issue for quite some time.

**Comment by bugsysop** [comment]
Same problem with last update, module did'nt render anymore on public site... No visible problem in the panel view.

**Comment by frekw** [comment]
I need more info to reproduce this since I'm not seeing it. Can you please provide a repo with a minimal test case?

**Comment by bugsysop** [comment]
It's just a quick and dirty try on MAMP.

First I tested with your Modules Exemple [here](https://github.com/frekw/kirby-modules-example). It whas working like a charm... apart from missing .htaccess file

Then I updated manualy the plugin an field... and now it work on backend but render nothing on front.

The rendered HTML from my page is exactly:

```
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1.0">

  <title>Kirby Starterkit | Home</title>
  <meta name="description" content="This is Kirby's Starterkit.">
  <meta name="keywords" content="Kirby, CMS, file-based">

  <link rel="stylesheet" href="http://localhost/kirby-modules/assets/css/main.css">  <link rel="stylesheet" href="http://localhost/kirby-modules/modules.css">  <script src="http://localhost/kirby-modules/modules.js"></script>
</head>
<body>

  <header class="header cf" role="banner">
    <a class="logo" href="http://localhost/kirby-modules">
      <img src="http://localhost/kirby-modules/assets/images/logo.svg" alt="Kirby Starterkit" />
    </a>
    <nav role="navigation">

  <ul class="menu cf">
      </ul>

</nav>
  </header>
  <main class="main" role="main">
    <h1>Home</h1>
    <p>Some body content.</p>    <div class="hero hero--align-
```

No modules, no footer, brutaly cut at `<div class="hero hero--align-`

**Comment by bugsysop** [comment]
Just tried with a fresh install of Starter Kit, exact same result !

I installed 2 fields (selector & modules) and one plugin (modules)
I inserted the necessary code in header & config files, and used the blueprint from your test package.

Configuration : MAMP 3.5 - PHP 5.6.10

**Comment by frekw** [comment]
Please provide the code if you want me to look at it.

Thanks!

**Comment by dirkschmid** [comment]
check out here:
https://github.com/dirkschmid/kib-mod-test

its the latest kirby with your latest plugin.

**Comment by bugsysop** [comment]
And this is mine.
https://github.com/bugsysop/kirby-modules-test

**Comment by frekw** [comment]
The example repo haven't been updated in a while. All module fields are now regular kirby fields, such calls like `$module->options->style->value()` should be `$module->options()->style()->value()` to work properly. I haven't gotten around to updating the example after that change. Just change all modules templates and it should be fine.

**Comment by dirkschmid** [comment]
works, thank you!

**Comment by bugsysop** [comment]
Works for me to... but not for nested modules.

All module (`hero, text, button`) works directly inserted in the page. `Text` and `button` modules, not showing when inserted (nested)  in `hero`.

I think the problem come from this portion of code in the `hero` template:

```
<?php if(isset($module->content)): ?>
    <?php echo $module->content->modules() ?>
<?php endif; ?>
```

I modified to this (with _no_ result):

```
<?php if(isset($module->content)): ?>
    <?php echo $module->content()->modules() ?>
 <?php endif; ?>
```

Thanks @frekw for your help and sweet plugin/field

**Comment by frekw** [comment]
Try `if($module->content()->isNotEmpty()):`

  -- F

**Comment by bugsysop** [comment]
No effect !

**Comment by frekw** [comment]
<?= $module->module_field_name()->modules() ?> 100% works.

**Comment by bugsysop** [comment]
Not for me :-(

Tried this:

```
<?php if($module->content()->isNotEmpty()): ?>
    <?php echo $module->module_field_name()->modules() ?>
 <?php endif; ?>
```

And this:

```
<?php if(isset($module->content)): ?>
     <?php echo $module->module_field_name()->modules() ?>
<?php endif; ?>
```

None worked

Juste commited my code on GH

**Comment by frekw** [comment]
That was just an example. The real code would be:

``` php
<?php if($module->content()->isNotEmpty())): ?>
     <?php echo $module->content()->modules() ?>
<?php endif; ?>
```

or just

``` php
<?php echo $module->content()->modules() ?>
```

Hope that helps.

I'm sorry to say, but this is a bug tracker – not a support forum. If you have programming related questions please refer to [StackOverflow](http://stackoverflow.com/questions/tagged/kirby) or [Kirby's support forum](forum.getkirby.com/)

**Comment by bugsysop** [comment]
Sorry.
