### ISSUE TITLE
Collapsable fields / Accordion

### ISSUE THREAD

**Issue by ghost** [frekw/kirby-modules#2]
Suggestion:
Add collapsable modules for easy reordering and overview..

**Comment by frekw** [comment]
Yup, that's planned!

**Comment by ghost** [comment]
Awesome! I kind of guessed that.. ;)

**Comment by frekw** [comment]
All modules are now accordions and collapsed by default. The styling is very minimal at the moment. I'll tweak it if I can think of a better design later!

**Comment by frekw** [comment]
On a second note, they are no longer collapsed by default. That was too annoying when editing content. But at least they can be collapsed :)

**Comment by ghost** [comment]
It would be great if they could remember the "state"(collapsed/not collapsed) they are in upon save.
Would be great for the tabs as well.(content/settings)

**Comment by frekw** [comment]
I want to keep the state out of the content itself – and I haven't come up with a way to do that yet that I'm satisfied with.

Might revisit it in the future!
