### ISSUE TITLE
Sorting value not updating

### ISSUE THREAD

**Issue by ghost** [frekw/kirby-modules#4]
Hi man,

Found an issue in the js file regarding to the sorted array not being saved/cached in the update function.

Test:
1. Add a 2-3 new modules.
2. Save
3. Rearrange/sort the modules (drag them around change order)
4. Add a new module.

Issue =  The nr 3 action does not store the positions of the rearranged modules..

**Comment by frekw** [comment]
I think I managed to find a work around for this in 
f3fa71cf2dc29c9adf273ff9eecb3f40dd34d287. Could you please verify?

**Comment by ghost** [comment]
Awesome works like a charm  = ) !!

**Comment by ghost** [comment]
The delete button as well...

```
element.find('> .modules-entries > .modules-entry .modules-entry-delete').on('click', function(){
     $(this).closest('form').trigger('keep');
});
```

**Comment by frekw** [comment]
:+1:
