### ISSUE TITLE
Invalid panel url in textarea buttons(link/mail).

### ISSUE THREAD

**Issue by ghost** [frekw/kirby-modules#8]
I know that the structure field, can´t open modals because it´s already in modal mode, but perhaps you can : ) !

![invalid](https://cloud.githubusercontent.com/assets/6350636/14427267/3cdeae46-fff4-11e5-8109-168e7305c241.png)

**Comment by ghost** [comment]
Drag and drop files from sidebar to textarea works fine though..

**Comment by frekw** [comment]
Unfortunately nothing that can be done without re-writing the field itself... :(
